### ISSUE TITLE
Include intermediate SPIRE certificate into ProxySQL chain

### ISSUE THREAD

**Issue by JavierJF** [thiagosantosleite/proxysql_test_tls_70224#1]
In order to test the changes introduced [by this commit](https://github.com/sysown/proxysql/pull/3552/commits/d5de8a52f1041b1d24b501ef0ed7f63b0a98e260). Intermediate certificate created by SPIRE needs to be added to ProxySQL CA certificate, so the chain is complete for verification, for doing this:

Once the certificates are created, split the `svid.0.pem` with the following command:
```
csplit -s -z -f individual- /tmp/svid.0.pem '/-----BEGIN CERTIFICATE-----/' '{*}'
```
Then append the resulting file `individual-01` at the begin of `proxysql-ca.pem` certificate:

```
cat individual-01 proxysql-ca.pem >> proxysql-ca.pem.tmp && mv proxysql-ca.pem.tmp proxysql-ca.pem
``` 

Now reload ProxySQL TLS (or not, depending if this is done at runtime or not).

Good to go!

**Comment by thiagosantosleite** [comment]
* Testing the spiffe with multiple dns 
```
make login-proxysql-spiffe-dns
```

* Added a new method to simulate an invalid login with different pki chain:

```
make login-proxysql-old-pki
```

* Following your request, now the copy method add the intermediate certificate to proxysql-ca.pem
* Added 3 methods to simplify the setup and tests
```
make all-ecdsa
or 
make all-rsa

make all-tests
```
